### ISSUE TITLE
yyparse multiple declarations

### ISSUE THREAD

**Issue by BurnZeZ** [tung/DynaHack#69]
/home/burnzez/Repos/UnNitroHack/libnitrohack/util/lev_comp.l:19:13: error: conflicting types for ‘yyparse’
/home/burnzez/Repos/UnNitroHack/build/libnitrohack/util/lev_comp.h:391:5: note: previous declaration of ‘yyparse’ was here
make[2]: **\* [libnitrohack/util/CMakeFiles/lev_comp.dir/lev_scanner.c.o] Error 1
make[1]: **\* [libnitrohack/util/CMakeFiles/lev_comp.dir/all] Error 2

Using commit 8b1f53053db5661e5ad6820940170d647d8d18a7

**Comment by tung** [comment]
Let me know if this fixes it. What OS are you building this on? I use Ubuntu 12.04 myself.

**Comment by BurnZeZ** [comment]
Yep, just confirmed the fix corrected the problem.
I'm on Gentoo x86_64 kernel 3.7.4, using the portage testing branch.
I compiled with gcc 4.6.3, and was using cmake 2.8.10.2-r1

Thanks for the quick fix.

**Comment by tung** [comment]
I did some testing. For some reason, my gcc, which is 4.6.3 just like your's, seems to permit mismatched return types for library functions so long as the return value at the call site is ignored, even with warnings enabled. Shame, I'd like to be able to catch issues like this myself. :|

Still, a fix is a fix.
