### ISSUE TITLE
Crashes when loading any game (windows x86)

### ISSUE THREAD

**Issue by SilearFlare** [tung/DynaHack#98]
Pretty groundbreaking problem. 

Savegames are saved in %appdata% Dynahack, trying to load a save crashes the game. 
Trying to move the saved games to dynahack's main folder and deleting appdata doesn't recognize the saves.
Trying to move every file to the appdata dyna folder doesn't change anything.
deleting every save and trying to load the game doesn't give any crashes.

I still don't know if it's a winx86 thing only, if someone would please try to check in win x64 we could get to the bottom of this.

Obviously since tung didn't  see this MAJOR bug before, I think I can safely say that it's windows only and linux works fine.

**Comment by gibboni** [comment]
Seems to be working just fine on Win 7 64bit and 32bit. I can not reproduce the problem.

**Comment by SilearFlare** [comment]
Must be a windows xp thing then. Thanks for confirming it!
Closing.
